# -*- coding: utf-8 -*-
"""Shopify Test

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18HloKRyF2Og5knbhjAK8i0ZJ9qVt7_HL
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns

df = pd.read_csv("/content/sample_data/shopify_stock.csv")
df

display(df.head())

df['date'] = pd.to_datetime(df['date'], utc=True)

fig = plt.figure(figsize=(14, 7))
sns.lineplot(x='date', y='close', data=df)
plt.title('Shopify Closing Price Over Time')
plt.xlabel('Date')
plt.ylabel('Closing Price')
plt.grid(True, linestyle='--', alpha=0.7)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

df['SMA_20'] = df['close'].rolling(window=20).mean()
df['SMA_50'] = df['close'].rolling(window=50).mean()
fig = plt.figure(figsize=(14, 7))
sns.lineplot(x='date', y='close', data=df, label='Closing Price', color='blue')
sns.lineplot(x='date', y='SMA_20', data=df, label='20-Day SMA', color='orange')
sns.lineplot(x='date', y='SMA_50', data=df, label='50-Day SMA', color='green')

plt.title('Shopify Closing Price with 20-Day and 50-Day Moving Averages')
plt.xlabel('Date')
plt.ylabel('Price')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.7)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

df['Daily_Return'] = df['close'].pct_change() * 100
df_returns = df.dropna(subset=['Daily_Return'])
fig = plt.figure(figsize=(10, 6))
sns.histplot(df_returns['Daily_Return'], bins=50, kde=False)
plt.title('Histogram of Daily Returns')
plt.xlabel('Daily Return (%)')
plt.ylabel('Frequency')
plt.grid(True, linestyle='--', alpha=0.7)

plt.tight_layout()
plt.show()

df['Daily_Return'] = df['close'].pct_change() * 100
df_returns = df.dropna(subset=['Daily_Return'])
fig = plt.figure(figsize=(10, 6))
sns.kdeplot(df_returns['Daily_Return'], fill=True)
plt.title('Kernel Density Estimate of Daily Returns')
plt.xlabel('Daily Return (%)')
plt.ylabel('Density')
plt.grid(True, linestyle='--', alpha=0.7)

plt.tight_layout()
plt.show()

